apps/core/urls.py
from django.urls import path, include
from .views.category.views import *
from .views.products.views import *
from .views.clients.views import *
from .views.sale.views import *

app_name = 'core'

urlpatterns = [
    # Category urls
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/edit/<int:pk>', CategoryUpdateView.as_view(), name='category_edit'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),

    # Product urls
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),

    # Clients urls
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),

    # Sales urls
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/create/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/edit/<int:pk>', SaleUpdateView.as_view(), name='sale_edit'),
    path('sale/delete/<int:pk>', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/invoice/<int:pk>', SaleInvocePdfView.as_view(), name='sale_invoice_pdf'),
]

apps/reports/urls.py
from django.urls import path, include
from .views import *


app_name = 'report'

urlpatterns = [
    path('sale/', ReportSaleView.as_view(), name='sale_report'),
]

apps/user/urls.py
from django.urls import path, include
from .views import *

app_name = 'user'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdate.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroupView.as_view(), name='user_change_group'),
    path('change/password/', UserChangePassword.as_view(), name='user_change_password'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.homepage.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('auth/', include('apps.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('apps.core.urls')),
    path('reports/', include('apps.reports.urls')),
    path('users/', include('apps.user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" {% block html %}data-layout="vertical" data-topbar="light" data-sidebar="light" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable"{% endblock html %}>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %} | Velzon - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    {% block css %}
    {% block extra_css %}
    {% endblock extra_css %}

    <!-- Layout config Js -->
    <script src="{% static 'js/layout.js'%}"></script>
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    
    <link href="{% static 'libs/sweetalert2/dist/sweetalert2.min.css'%}" rel="stylesheet" type="text/css" />
    {% endblock css %}
</head>

<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        {% block header %}
        {% include "partials/topbar.html" %}
        {% endblock header %}
        {% block sidebar %}
        {% include "partials/sidebar.html" %}
        {% endblock sidebar %}
        {% block content %}
        {% block pagetitle %}
        {% endblock pagetitle %}
        {% block footer %}
        {% endblock footer %}
        {% endblock content %}
    </div>
    
    {% block extra_content %}        
    {% endblock extra_content %}
        
    <!-- END layout-wrapper -->
    {% block right_sidebar %}
    {% include "partials/customizer.html" %}
    {% endblock right_sidebar %}

    {% block javascript %}
    <!-- JAVASCRIPT -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--datatable js-->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
    <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
    <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
    <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/modal.js'%}"></script>
    <!-- Sweet Alerts js -->
    <script src="{% static 'libs/sweetalert2/dist/sweetalert2.min.js'%}"></script>


    {% block extra_js %}
    {% endblock extra_js %}

    <!-- App js -->
    <script src="{% static 'js/app.js'%}"></script>
    {% endblock javascript %}
    <script>
        // Usar messages con sweetalert
        {% if messages %}
            let messageText = "";
            {% for message in messages %}
            messageText += "{{ message }}<br>";
            Swal.fire({
                icon: "{{ message.tags }}",
                title: "{{ message.tags }}" == "error" ? "Error!" : "{{ message.tags }}" == "warning" ? "Advertencia" : "{{ message.tags }}" == "success" ? "Éxito" : "Información",
                html: messageText
            });
            {% endfor %}
        {% endif %}
    </script>
</body>

</html>

templates/partials/footer.html
{% block footer %}
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Velzon.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Design & Develop by Themesbrand
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
{% endblock footer %}
    

templates/partials/page-title.html
<!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0">{{title}}</h4>

                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">{{pagetitle}}</a></li>
                                        <li class="breadcrumb-item active">{{title}}</li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->
                    

templates/partials/sidebar.html
{% load static %}
{% block sidebar %}
        <!-- ========== App Menu ========== -->
        <div class="app-menu navbar-menu">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <!-- Dark Logo-->
                <a href="/" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-dark.png'%}" alt="" height="17">
                    </span>
                </a>
                <!-- Light Logo-->
                <a href="/" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-light.png'%}" alt="" height="17">
                    </span>
                </a>
                <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
                    <i class="ri-record-circle-line"></i>
                </button>
            </div>

            <div id="scrollbar">
                <div class="container-fluid">
                    
                    <div id="two-column-menu">
                    </div>
                    <ul class="navbar-nav" id="navbar-nav">
                        <!-- Title Menu -->
                        <li class="menu-title"><span data-key="t-menu">Mantenimiento</span></li>

                        <!-- Categories -->
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarCategories" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarCategories">
                                <i data-feather="grid" class="icon-dual"></i> <span data-key="t-categories">Categorias</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarCategories">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'core:category_list' %}" class="nav-link" data-key="t-categories-list"> Listado </a>
                                    </li>
                                    
                                    <li class="nav-item">
                                        <a href="{% url 'core:category_create' %}" class="nav-link" data-key="t-categories-add"> Añadir </a>
                                    </li>
                                </ul>
                            </div>
                        </li> 

                        <!-- Products -->
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarProducts" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarProducts">
                                <i data-feather="box" class="icon-dual"></i> <span data-key="t-products">Productos</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarProducts">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'core:product_list' %}" class="nav-link" data-key="t-products-list"> Listado </a>
                                    </li>
                                    
                                    <li class="nav-item">
                                        <a href="{% url 'core:product_create' %}" class="nav-link" data-key="t-products-add"> Añadir </a>
                                    </li>
                                </ul>
                            </div>
                        </li> 

                        <!-- Clients -->
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarClient" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarClient">
                                <i data-feather="users" class="icon-dual"></i> <span data-key="t-client">Clientes</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarClient">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'core:client_list' %}" class="nav-link" data-key="t-client-list"> Listado </a>
                                    </li>
                                    
                                    <li class="nav-item">
                                        <a href="{% url 'core:client_create' %}" class="nav-link" data-key="t-client-add"> Añadir </a>
                                    </li>
                                </ul>
                            </div>
                        </li>

                        <!-- Sales -->
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarSales" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarSales">
                                <i data-feather="shopping-bag" class="icon-dual"></i> <span data-key="t-client">Ventas</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarSales">
                                <ul class="nav nav-sm flex-column">
                                    
                                    <li class="nav-item">
                                        <a href="{% url 'core:sale_list' %}" class="nav-link" data-key="t-client-list">Listado</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="collapse menu-dropdown" id="sidebarSales">
                                <ul class="nav nav-sm flex-column">
                                    
                                    <li class="nav-item">
                                        <a href="{% url 'core:sale_create' %}" class="nav-link" data-key="t-client-add">Añadir</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarReports" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarReports">
                                <i data-feather="bar-chart-2" class="icon-dual"></i> <span data-key="t-report">Reportes</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarReports">
                                <ul class="nav nav-sm flex-column">
                                    
                                    <li class="nav-item">
                                        <a href="{% url 'report:sale_report' %}" class="nav-link" data-key="t-report-sales">Ventas</a>
                                    </li>
                                </ul>
                            </div>
                        </li>

                        
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarUsers" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarUsers">
                                <i data-feather="users" class="icon-dual"></i> <span data-key="t-user">Usuarios</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarUsers">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'user:user_create' %}" class="nav-link" data-key="t-user-add">Añadir</a>
                                    </li>
                                </ul>
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'user:user_list' %}" class="nav-link" data-key="t-user-list">Listado</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- Sidebar -->
            </div>
            <div class="sidebar-background"></div>
        </div>
        <!-- Left Sidebar End -->
        <!-- Vertical Overlay-->
        <div class="vertical-overlay"></div>
{% endblock sidebar %}
    